-- Update schools table to add province column if it doesn't exist
ALTER TABLE public.schools ADD COLUMN IF NOT EXISTS province text;

-- Insert schools from the Excel file with province data
-- Using INSERT ON CONFLICT to avoid duplicates
INSERT INTO public.schools (name, province, status) VALUES
('Affies', 'Gauteng', 'verified'),
('Bellville', 'Western Cape', 'verified'),
('Bishops', 'Western Cape', 'verified'),
('Boland Landbou', 'Western Cape', 'verified'),
('Bosmansdam', 'Unknown', 'verified'),
('Brackenfell', 'Western Cape', 'verified'),
('CBC Boksburg', 'Gauteng', 'verified'),
('Charlie Hofmeyr', 'Unknown', 'verified'),
('Clifton', 'KwaZulu-Natal', 'verified'),
('Daniel Pienaar', 'Unknown', 'verified'),
('DF Malan', 'Unknown', 'verified'),
('Diamantveld', 'Unknown', 'verified'),
('Drostdy', 'Western Cape', 'verified'),
('Durban HS', 'KwaZulu-Natal', 'verified'),
('Durbanville', 'Western Cape', 'verified'),
('EG Jansen', 'Unknown', 'verified'),
('Framesby', 'Western Cape', 'verified'),
('Garsfontein', 'Unknown', 'verified'),
('Glenwood', 'KwaZulu-Natal', 'verified'),
('Grey College', 'Free State', 'verified'),
('Grey HS', 'Unknown', 'verified'),
('Helpmekaar', 'Unknown', 'verified'),
('Hermanus', 'Western Cape', 'verified'),
('Hillcrest High School', 'KwaZulu-Natal', 'verified'),
('Hilton', 'KwaZulu-Natal', 'verified'),
('Hilton College', 'KwaZulu-Natal', 'verified'),
('Hopefield', 'Unknown', 'verified'),
('Hottentots Holland', 'Western Cape', 'verified'),
('HTS Bellville', 'Western Cape', 'verified'),
('Hugenote', 'Western Cape', 'verified'),
('Jeppe', 'Gauteng', 'verified'),
('Kearsney', 'KwaZulu-Natal', 'verified'),
('KES', 'Gauteng', 'verified'),
('Mali XV', 'Unknown', 'verified'),
('Maritzburg College', 'KwaZulu-Natal', 'verified'),
('Melkbosstrand', 'Western Cape', 'verified'),
('Menlopark', 'Unknown', 'verified'),
('Michaelhouse', 'KwaZulu-Natal', 'verified'),
('Milnerton', 'Western Cape', 'verified'),
('Monument', 'Unknown', 'verified'),
('Monument Park', 'Unknown', 'verified'),
('Nico Malan', 'Unknown', 'verified'),
('Noordheuwel', 'Unknown', 'verified'),
('Northcliff', 'Unknown', 'verified'),
('Northwood', 'KwaZulu-Natal', 'verified'),
('Oakdale', 'Western Cape', 'verified'),
('Outeniqua', 'Western Cape', 'verified'),
('Paarl BH', 'Western Cape', 'verified'),
('Paarl Boys High', 'Western Cape', 'verified'),
('Paarl Gim', 'Western Cape', 'verified'),
('Paarl Gimnasium', 'Western Cape', 'verified'),
('Parel Vallei', 'Unknown', 'verified'),
('Parktown', 'Unknown', 'verified'),
('Paul Roos', 'Western Cape', 'verified'),
('Pearson', 'Unknown', 'verified'),
('Pretoria BH', 'Gauteng', 'verified'),
('Punt', 'Unknown', 'verified'),
('Queen''s', 'Unknown', 'verified'),
('Rondebosch', 'Western Cape', 'verified'),
('Rustenburg', 'Unknown', 'verified'),
('SACS', 'Western Cape', 'verified'),
('Springs', 'Unknown', 'verified'),
('St Alban''s', 'Gauteng', 'verified'),
('St Andrew''s Sch', 'Eastern Cape', 'verified'),
('St Benedict''s', 'Unknown', 'verified'),
('St Charles', 'KwaZulu-Natal', 'verified'),
('St David''s', 'Gauteng', 'verified'),
('St David''s / St Charles', 'Unknown', 'verified'),
('St John''s', 'Unknown', 'verified'),
('St Stithians', 'Unknown', 'verified'),
('Stellenberg', 'Unknown', 'verified'),
('Strand', 'Unknown', 'verified'),
('Swartland', 'Unknown', 'verified'),
('Trinityhouse', 'Unknown', 'verified'),
('Tygerberg', 'Unknown', 'verified'),
('Waterkloof', 'Unknown', 'verified'),
('Westville', 'Unknown', 'verified'),
('Worcester Gim', 'Unknown', 'verified'),
('Wynberg', 'Unknown', 'verified')
ON CONFLICT (name) DO UPDATE SET
  province = EXCLUDED.province,
  status = EXCLUDED.status;